I HAS A PEN
I HAS A APPLE

PEN R "PEN"
APPLE R "APPLE "

VISIBLE SMOOSH APPLE AN PEN

I HAS A PEN
I HAS A PINEAPPLE

PEN R "PEN "
PINEAPPLE R "PINEAPPLE "

VISIBLE SMOOSH PINEAPPLE AN PEN

I HAS A APPLE_PEN
I HAS A PINEAPPLE_PEN

APPLE_PEN R SMOOSH APPLE AN PEN
PINEAPPLE_PEN R SMOOSH PINEAPPLE AN PEN

VISIBLE SMOOSH PEN AN PINEAPPLE AN APPLE AN PEN